name: master-cd

on:
  push:
    branches: [ master ]
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build bundle
        run: CI=false PUBLIC_URL=./ yarn run build

      - name: Upload bundle
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_PRD_HOST }}
          username: ${{ secrets.SSH_PRD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build"
          target: "~"
          
      - name: Upgrade apps
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo cp -rf build /usr/
            sudo rm -rf build
          host: ${{ secrets.SSH_PRD_HOST }}
          user: ${{ secrets.SSH_PRD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pin to IPFS
        id: upload
        uses: crustio/ipfs-upload-action@v2.0.2
        with:
          path: './build'
          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Place storage order on Crust
        uses: crustio/ipfs-crust-action@v2.0.3
        timeout-minutes: 2
        with:
          cid: ${{ steps.upload.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Update DNS with new IPFS hash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'crustapps.net'
          RECORD_NAME: '_dnslink'
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        uses: textileio/cloudflare-update-dnslink@0fe7b7a1ffc865db3a4da9773f0f987447ad5848
        with:
          cid: ${{ steps.upload.outputs.hash }}
      
